### ISSUE TITLE
Ethereal Issue

### ISSUE THREAD

**Issue by Lunaraia** [t-larson/BaseMod#11]
Nemesis' reworked Ethereal status effect causes the game to run into an exception, no ingame error log is created but the console thingy you setup returns the following error:

Exception: java.lang.ArrayIndexOutOfBoundsException: 2
01:14:09.252 [LWJGL Application] ERROR com.megacrit.cardcrawl.core.CardCrawlGame - Exception caught
java.lang.ArrayIndexOutOfBoundsException: 2
	at com.megacrit.cardcrawl.powers.IntangiblePower.updateDescription(IntangiblePower.java:57) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.powers.IntangiblePower.<init>(IntangiblePower.java:29) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.monsters.thebeyond.Nemesis.takeTurn(Nemesis.java:89) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.monsters.MonsterGroup.takeTurn(MonsterGroup.java:126) ~[BaseMod.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.getNextAction(GameActionManager.java:270) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:143) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:241) ~[desktop-1.0.jar:?]
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2388) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:769) ~[?:?]
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:364) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225) [?:?]
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126) [desktop-1.0.jar:?]
Game closed.

This causes the game to auto close and I am certain it's Nemesis' Ethereal status that does it as this is the 4th time this has happened and it has only happened just as Nemesis enters the first turn where he uses Ethereal

**Comment by daviscook477** [comment]
Thanks for the heads up! I'll take a look at what's causing that index out of bounds exception later today.
