### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by danickfort** [t-larson/BaseMod#13]
I'm getting this stacktrace when launching the mod with Mod the Spire. I'm on Windows 10, the game is on version early_access_015.

> Finding core patches...
Patch [com.evacipated.cardcrawl.modthespire.patches.DisableGdxForceExit]
  Patching [com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop]
    Adding Insert @ 248...
{
com.evacipated.cardcrawl.modthespire.patches.DisableGdxForceExit.Insert($0, $$);
}
Patch [com.evacipated.cardcrawl.modthespire.patches.MainMenuModList]
  Patching [com.megacrit.cardcrawl.screens.mainMenu.MainMenuScreen.render]
    Adding Postfix...
      com.evacipated.cardcrawl.modthespire.patches.MainMenuModList.Postfix($0, $$);
Patch [com.evacipated.cardcrawl.modthespire.patches.TopPanelModList]
  Patching [com.megacrit.cardcrawl.ui.panels.TopPanel.updateTips]
    Adding Postfix...
      com.evacipated.cardcrawl.modthespire.patches.TopPanelModList.Postfix($0, $$);
Patch [com.evacipated.cardcrawl.modthespire.patches.CreditsModList]
  Patching [com.megacrit.cardcrawl.credits.CreditsScreen.ctor]
    Adding Insert @ r5 (abs:55)...
{
float[] __tmpY = new float[]{tmpY};
com.evacipated.cardcrawl.modthespire.patches.CreditsModList.Insert($0, $$, __tmpY);
tmpY = __tmpY[0];
}
Finding patches...
Patch [basemod.patches.com.megacrit.cardcrawl.characters.AbstractPlayer.GetTitleSwitch]
  Patching [com.megacrit.cardcrawl.characters.AbstractPlayer.getTitle]
    Adding Postfix...
      Return: java.lang.Object
      Result param: java.lang.Object
      return ($r)basemod.patches.com.megacrit.cardcrawl.characters.AbstractPlayer.GetTitleSwitch.Postfix($_, $$);
Patch [basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.RenderEnergySwitch]
  Patching [com.megacrit.cardcrawl.cards.AbstractCard.renderEnergy]
    Adding Insert @ 2545...
{
basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.RenderEnergySwitch.Insert($0, $$, drawX, drawY);
}
Patch [basemod.patches.com.megacrit.cardcrawl.characters.AbstractPlayer.PostInitializeStarterRelicsHookSwitch]
  Patching [com.megacrit.cardcrawl.characters.AbstractPlayer.initializeStarterRelics]
    Adding Insert @ 271...
{
java.util.ArrayList[] __relics = new java.util.ArrayList[]{relics};
basemod.patches.com.megacrit.cardcrawl.characters.AbstractPlayer.PostInitializeStarterRelicsHookSwitch.Insert($0, $$, __relics);
relics = __relics[0];
}
Patch [basemod.patches.com.megacrit.cardcrawl.helpers.RelicLibrary.EditRelicsPatch]
  Patching [com.megacrit.cardcrawl.helpers.RelicLibrary.initialize]
    Adding Prefix...
{
basemod.patches.com.megacrit.cardcrawl.helpers.RelicLibrary.EditRelicsPatch.Prefix();
}
Patch [basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.PostUpdateHook]
  Patching [com.megacrit.cardcrawl.core.CardCrawlGame.update]
    Adding Insert @ 792...
{
basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.PostUpdateHook.Insert($0, $$);
}
Patch [basemod.patches.com.megacrit.cardcrawl.powers.IntangiblePower.FixPlayerIntangiblePower]
  Patching [com.megacrit.cardcrawl.powers.IntangiblePower.atEndOfTurn]
    Adding Instrument...
Patch [basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.RenderHook]
  Patching [com.megacrit.cardcrawl.core.CardCrawlGame.render]
    Adding Insert @ 395...
{
basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.RenderHook.Insert($0, $$, sb);
}
Patch [basemod.patches.com.megacrit.cardcrawl.rooms.CampfireUI.InitializeButtonsSwitch]
  Patching [com.megacrit.cardcrawl.rooms.CampfireUI.initializeButtons]
    Adding Insert @ 71...
{
basemod.patches.com.megacrit.cardcrawl.rooms.CampfireUI.InitializeButtonsSwitch.Insert($0, $$);
}
Patch [basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.PreStartGameHook]
  Patching [com.megacrit.cardcrawl.core.CardCrawlGame.update]
    Adding Insert @ 697...
{
basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.PreStartGameHook.Insert($0, $$);
}
Patch [basemod.patches.com.megacrit.cardcrawl.ui.panels.DrawPilePanel.DrawPilePanelConsoleCheck]
  Patching [com.megacrit.cardcrawl.ui.panels.DrawPilePanel.updatePositions]
    Adding Instrument...
Patch [basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.GreenCardsPatch]
  Patching [com.megacrit.cardcrawl.helpers.CardLibrary.addGreenCards]
    Adding Postfix...
      basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.GreenCardsPatch.Postfix($$);
Patch [basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.StartActHook]
  Patching [com.megacrit.cardcrawl.core.CardCrawlGame.update]
    Adding Insert @ 778...
{
basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.StartActHook.Insert($0, $$);
}
Patch [basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.RenderAttackBgSwitch]
  Patching [com.megacrit.cardcrawl.cards.AbstractCard.renderAttackBg]
    Adding Postfix...
      basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.RenderAttackBgSwitch.Postfix($0, $$);
Patch [basemod.patches.com.megacrit.cardcrawl.screens.charSelect.CharacterSelectScreen.InitializeSwitch]
  Patching [com.megacrit.cardcrawl.screens.charSelect.CharacterSelectScreen.initialize]
    Adding Insert @ 66...
{
basemod.patches.com.megacrit.cardcrawl.screens.charSelect.CharacterSelectScreen.InitializeSwitch.Insert($0, $$);
}
Patch [basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.RenderOuterGlowSwitch]
  Patching [com.megacrit.cardcrawl.cards.AbstractCard.renderOuterGlow]
    Adding Insert @ 1237...
{
basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.RenderOuterGlowSwitch.Insert($0, $$);
}
Patch [basemod.patches.com.megacrit.cardcrawl.ui.campfire.AbstractCampfireOption.PostCampfireHook]
  Patching [com.megacrit.cardcrawl.ui.campfire.AbstractCampfireOption.update]
    Adding Instrument...
Patch [basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.CreateCardImageSwitch]
  Patching [com.megacrit.cardcrawl.cards.AbstractCard.createCardImage]
    Adding Insert @ 844...
{
basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.CreateCardImageSwitch.Insert($0, $$);
}
Patch [basemod.patches.com.megacrit.cardcrawl.map.MapGenerator.PathDensityMultiplier]
  Patching [com.megacrit.cardcrawl.map.MapGenerator.generateDungeon]
    Adding Instrument...
Patch [basemod.patches.com.megacrit.cardcrawl.ui.buttons.EndTurnButton.EndTurnButtonConsoleCheck]
  Patching [com.megacrit.cardcrawl.ui.buttons.EndTurnButton.update]
    Adding Instrument...
Patch [basemod.patches.com.megacrit.cardcrawl.vfx.CardTrailEffect.CtorSwitch]
  Patching [com.megacrit.cardcrawl.vfx.CardTrailEffect.ctor]
    Adding Postfix...
      basemod.patches.com.megacrit.cardcrawl.vfx.CardTrailEffect.CtorSwitch.Postfix($0, $$);
Patch [basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.InitializeCardPoolsSwitch]
  Patching [com.megacrit.cardcrawl.dungeons.AbstractDungeon.initializeCardPools]
    Adding Insert @ 1393...
{
basemod.patches.com.megacrit.cardcrawl.dungeons.AbstractDungeon.InitializeCardPoolsSwitch.Insert($0, $$, tmpPool);
}
Patch [basemod.patches.com.megacrit.cardcrawl.core.EnergyManager.PostEnergyRechargeHook]
  Patching [com.megacrit.cardcrawl.core.EnergyManager.recharge]
    Adding Insert @ 39...
{
basemod.patches.com.megacrit.cardcrawl.core.EnergyManager.PostEnergyRechargeHook.Insert($0, $$);
}
Patch [basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.GetCardListSwitch]
  Patching [com.megacrit.cardcrawl.helpers.CardLibrary.getCardList]
    Adding Insert @ 693...
{
basemod.patches.com.megacrit.cardcrawl.helpers.CardLibrary.GetCardListSwitch.Insert($$, retVal);
}
Patch [basemod.patches.com.megacrit.cardcrawl.localization.LocalizedStrings.EditStrings]
  Patching [com.megacrit.cardcrawl.localization.LocalizedStrings.ctor]
    Adding Postfix...
      basemod.patches.com.megacrit.cardcrawl.localization.LocalizedStrings.EditStrings.Postfix($0, $$);
Patch [basemod.patches.com.megacrit.cardcrawl.shop.ShopScreen.PostCreateShopPotionHook]
  Patching [com.megacrit.cardcrawl.shop.ShopScreen.initPotions]
    Adding Postfix...
      basemod.patches.com.megacrit.cardcrawl.shop.ShopScreen.PostCreateShopPotionHook.Postfix($0, $$);
Patch [basemod.patches.com.megacrit.cardcrawl.ui.panels.EnergyPanel.RenderOrbSwitch]
  Patching [com.megacrit.cardcrawl.ui.panels.EnergyPanel.renderOrb]
    Adding Postfix...
      basemod.patches.com.megacrit.cardcrawl.ui.panels.EnergyPanel.RenderOrbSwitch.Postfix($0, $$);
Patch [basemod.patches.com.megacrit.cardcrawl.ui.panels.DiscardPilePanel.DiscardPilePanelConsoleCheck]
  Patching [com.megacrit.cardcrawl.ui.panels.DiscardPilePanel.updatePositions]
    Adding Instrument...
Patch [basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.RenderPowerBgSwitch]
  Patching [com.megacrit.cardcrawl.cards.AbstractCard.renderPowerBg]
    Adding Postfix...
      basemod.patches.com.megacrit.cardcrawl.cards.AbstractCard.RenderPowerBgSwitch.Postfix($0, $$);
Patch [basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.CreateCharacterSwitch]
  Patching [com.megacrit.cardcrawl.core.CardCrawlGame.createCharacter]
    Adding Insert @ 980...
{
java.lang.Object[] __p = new java.lang.Object[]{p};
basemod.patches.com.megacrit.cardcrawl.core.CardCrawlGame.CreateCharacterSwitch.Insert($$, __p);
p = (com.megacrit.cardcrawl.characters.AbstractPlayer)__p[0];
}
javassist.CannotCompileException: [source error] no such field: p
	at javassist.CtBehavior.insertAt(CtBehavior.java:1213)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1140)
	at com.evacipated.cardcrawl.modthespire.Patcher.addInsert(Patcher.java:370)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:190)
	at com.evacipated.cardcrawl.modthespire.Patcher.injectPatches(Patcher.java:127)
	at com.evacipated.cardcrawl.modthespire.Loader.runMods(Loader.java:79)
	at com.evacipated.cardcrawl.modthespire.ModSelectWindow.lambda$null$0(ModSelectWindow.java:83)
	at java.lang.Thread.run(Unknown Source)
Caused by: compile error: no such field: p
	at javassist.compiler.TypeChecker.fieldAccess(TypeChecker.java:845)
	at javassist.compiler.TypeChecker.atFieldRead(TypeChecker.java:803)
	at javassist.compiler.TypeChecker.atMember(TypeChecker.java:988)
	at javassist.compiler.JvstTypeChecker.atMember(JvstTypeChecker.java:66)
	at javassist.compiler.ast.Member.accept(Member.java:39)
	at javassist.compiler.TypeChecker.atArrayInit(TypeChecker.java:186)
	at javassist.compiler.ast.ArrayInit.accept(ArrayInit.java:29)
	at javassist.compiler.TypeChecker.atNewArrayExpr(TypeChecker.java:162)
	at javassist.compiler.TypeChecker.atNewExpr(TypeChecker.java:144)
	at javassist.compiler.ast.NewExpr.accept(NewExpr.java:73)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atDeclarator(CodeGen.java:743)
	at javassist.compiler.ast.Declarator.accept(Declarator.java:100)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.Javac.compileStmnt(Javac.java:567)
	at javassist.CtBehavior.insertAt(CtBehavior.java:1192)
	... 7 more

**Comment by danickfort** [comment]
Forget it, did not have the latest STS patch .
